CREATE TABLE match
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    match_date  date                                    NOT NULL,
    match_time  time WITHOUT TIME ZONE                  NOT NULL,
    team_a      VARCHAR(255)                            NOT NULL,
    team_b      VARCHAR(255)                            NOT NULL,
    sport       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_match PRIMARY KEY (id)
);
CREATE TABLE match_odd
(
    id        BIGINT           NOT NULL,
    match_id  BIGINT           NOT NULL,
    specifier VARCHAR(50)      NOT NULL,
    odd       DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_match_odd PRIMARY KEY (id)
);

ALTER TABLE match_odd
    ADD CONSTRAINT FK_MATCH_ODD_ON_MATCH FOREIGN KEY (match_id) REFERENCES match (id);